#!/bin/bash

MYNAME=sanidoc

set -o pipefail

IMG=dz2

INFILE=/dev/stdin

PODMAN="podman run --read-only --rm --network=none --cap-drop=ALL -i $MYNAME"

if [ -z "$1" ]; then
	if [ -t 0 ]; then
		echo "error: stdin is a terminal. exiting." 1>&2
		exit 1
	fi
else
	INFILE="$1"
	if [ ! -e "$INFILE" ]; then
		echo "error: no such input file." 1>&2
		exit 1
	fi
fi

if [ -t 1 ]; then
	echo "error: stdout is a terminal. exiting." 1>&2
	exit 1
fi


#./stage1 < "$INFILE" | ./stage2

$PODMAN /opt/$MYNAME/stage1 < "$INFILE" | $PODMAN /opt/$MYNAME/stage2
if [ $? -ne 0 ]; then
	echo "error: conversion failed." 1>&2
	exit $?
fi
